steps:
  - name: 'gcr.io/cloud-builders/gcloud:latest'
  - args: ['auth', 'configure-docker']
  - name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
    id: build
    args: ['clean', 'install', 'jib:build']
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - run
      - --image=gcr.io/${PROJECT_ID}/guestbook-service:latest
      - --location=us-central1-a
      - --cluster=standard-cluster-1
      - --expose=8080
timeout: "1600s"
